# Generated by Django 5.2.12 on 2026-05-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='has_projector',
            field=models.BooleanField(default=False, verbose_name='Наличие проектора'),
        ),
    ]
