# Generated by Django 5.2.14 on 2026-05-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на аватар'),
        ),
    ]
